In [1]:
import pandas as pd

In [2]:
aki_df = pd.read_excel("AI_for_AKI_list.xlsx", sheet_name='AKI genes')
nash_df = pd.read_excel("AI_for_AKI_list.xlsx", sheet_name='NASH genes')

In [3]:
aki_df.head()

,Protein name,Pharos protein classification,Uniport ID,# of ligands in Pharos,# of approved drugs,# of ligands in ChEMBL,# of ligands in SureChEMBL,Unnamed: 7,Gene name,notes
0,Interleukin-19,Tbio,Q9UHD0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,Interleukin-6,Tclin,P05231,10.0,1.0,NaN,NaN,NaN,NaN,NaN
2,STAT3,Tchem,P40763,85.0,2.0,NaN,NaN,NaN,NaN,NaN
3,Twist2,Tbio,Q8WVJ9,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,Oat5,Tdark,Q63ZE4,0.0,0.0,NaN,NaN,NaN,SLC22A10,NaN

In [4]:
nash_df.head()

,Protein name,Pharos protein classification,Uniport ID,# of ligands in Pharos,# of approved drugs,# of ligands in ChEMBL,# of ligands in SureChEMBL,Gene name,notes
0,Ppar𝛂,Tclin,Q07869,368.0,9.0,NaN,NaN,PPARA,NaN
1,Fabp5,Tchem,Q01469,13.0,1.0,NaN,NaN,FABP5,NaN
2,Cpt1𝛂,Tchem,P50416,472.0,NaN,NaN,NaN,CPT1A,double check the gene id
3,Acox,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"There are bunch of ACOX proteins, ACOX1, AXCOX..."
4,scd-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,there is scd and scd5 but not scd-1

### Check if there is any model in Ligandnet

In [5]:
models = pd.read_csv("../model_info.csv")
models.head()

,id,name,tdl,fam,famext,uniprot_name,description,uniprot,seq,sym
0,23,3 beta-hydroxysteroid dehydrogenase/Delta 5-->...,Tchem,Enzyme,3-beta-HSD,3BHS1_HUMAN,3 beta-hydroxysteroid dehydrogenase/Delta 5-->...,P14060,MTGWSCLVTGAGGFLGQRIIRLLVKEKELKEIRVLDKAFGPELREE...,HSD3B1
1,26,5-hydroxytryptamine receptor 2B,Tclin,GPCR,GPCR,5HT2B_HUMAN,5-hydroxytryptamine receptor 2B,P41595,MALSYRVSELQSTIPEHILQSTFVHVISSNWSGLQTESIPEEMKQI...,HTR2B
2,27,5-hydroxytryptamine receptor 2C,Tclin,GPCR,GPCR,5HT2C_HUMAN,5-hydroxytryptamine receptor 2C,P28335,MVNLRNAVHSFLVHLIGLLVWQCDISVSPVAAIVTDIFNTSDGGRF...,HTR2C
3,30,5'-nucleotidase,Tchem,Enzyme,NaN,5NTD_HUMAN,5'-nucleotidase,P21589,MCPRAARAPATLLLALGAVLWPAAGAWELTILHTNDVHSRLEQTSE...,NT5E
4,39,Adenosine receptor A3,Tchem,GPCR,GPCR,AA3R_HUMAN,Adenosine receptor A3,P0DMS8,MPNNSTALSLANVTYITMEIFIGLCAIVGNVLVICVVKLNPSLQTT...,ADORA3

In [7]:
models[models.uniprot.isin(aki_df['Uniport ID'])]

Empty DataFrame
Columns: [id, name, tdl, fam, famext, uniprot_name, description, uniprot, seq, sym]
Index: []

In [6]:
models[models.uniprot.isin(nash_df['Uniport ID'])]

,id,name,tdl,fam,famext,uniprot_name,description,uniprot,seq,sym
217,3460,"Carnitine O-palmitoyltransferase 1, liver isoform",Tchem,Enzyme,carnitine/choline_acetyltransferase,CPT1A_HUMAN,"Carnitine O-palmitoyltransferase 1, liver isoform",P50416,MAEAHQAVAFQFTVTPDGIDLRLSHEALRQIYLSGLHSWKKKFIRF...,CPT1A
301,5557,"Fatty acid-binding protein, epidermal",Tchem,NaN,NaN,FABP5_HUMAN,"Fatty acid-binding protein, epidermal",Q01469,MATVQQLEGRWRLVDSKGFDEYMKELGVGIALRKMGAMAKPDCIIT...,FABP5
587,10908,Microsomal triglyceride transfer protein large...,Tclin,NaN,NaN,MTP_HUMAN,Microsomal triglyceride transfer protein large...,P55157,MILLAVLFLCFISSYSASVKGHTTGLSLNNDRLYKLTYSTEVLLDR...,MTTP
724,13566,Peroxisome proliferator-activated receptor alpha,Tclin,NR,NR,PPARA_HUMAN,Peroxisome proliferator-activated receptor alpha,Q07869,MVDTESPLCPLSPLEAGDLESPLSEEFLQEMGNIQEISQSIGEDSS...,PPARA

In [6]:
models[models.name.isin(nash_df['Protein name'])]

Empty DataFrame
Columns: [id, name, tdl, fam, famext, uniprot_name, description, uniprot, seq, sym]
Index: []

In [7]:
models[models.name.isin(aki_df['Protein name'])]

Empty DataFrame
Columns: [id, name, tdl, fam, famext, uniprot_name, description, uniprot, seq, sym]
Index: []

Nothing!!!

### Search in the chembl dataset to find active ligands for the proteins

In [8]:
import mysql.connector as sql
db_connection = sql.connect(host='129.108.3.163', db='chembl25', user='tcrd', password='tcrd')

In [9]:
db_cursor = db_connection.cursor()

#### Find AKI proteins

In [17]:
query = 'SELECT * FROM target_dictionary'
target_df = pd.read_sql(query, con=db_connection)
target_df.head()

,tid,target_type,pref_name,tax_id,organism,chembl_id,species_group_flag
0,1,SINGLE PROTEIN,Maltase-glucoamylase,9606.0,Homo sapiens,CHEMBL2074,0
1,2,SINGLE PROTEIN,Sulfonylurea receptor 2,9606.0,Homo sapiens,CHEMBL1971,0
2,3,SINGLE PROTEIN,Phosphodiesterase 5A,9606.0,Homo sapiens,CHEMBL1827,0
3,4,SINGLE PROTEIN,Voltage-gated T-type calcium channel alpha-1H ...,9606.0,Homo sapiens,CHEMBL1859,0
4,5,SINGLE PROTEIN,Nicotinic acetylcholine receptor alpha subunit,6253.0,Ascaris suum,CHEMBL1884,0

In [18]:
target_df[target_df.pref_name.isin(aki_df["Protein name"])]

,tid,target_type,pref_name,tax_id,organism,chembl_id,species_group_flag
7495,104029,SINGLE PROTEIN,Interleukin-18,9606.0,Homo sapiens,CHEMBL1741305,0
7496,104033,SINGLE PROTEIN,Osteopontin,9606.0,Homo sapiens,CHEMBL1741309,0
7636,104209,SINGLE PROTEIN,Interleukin-6,9606.0,Homo sapiens,CHEMBL1795129,0
7860,104460,SINGLE PROTEIN,Midkine,9606.0,Homo sapiens,CHEMBL1949490,0

#### Find ligand activity using tid

tid = 104209

In [19]:
query = "SELECT m.chembl_id AS compound_chembl_id,   \
s.canonical_smiles,   \
r.compound_key,   \
a.description                   AS assay_description,   act.standard_type,   \
act.standard_relation,   \
act.standard_value,   \
act.standard_units,   \
act.activity_comment \
FROM compound_structures s,   \
molecule_dictionary m,   \
compound_records r,   \
docs d,   \
activities act,   \
assays a,   \
target_dictionary t \
WHERE s.molregno     = m.molregno \
AND m.molregno       = r.molregno \
AND r.record_id      = act.record_id \
AND r.doc_id         = d.doc_id \
AND act.assay_id     = a.assay_id \
AND a.tid            = t.tid \
AND t.tid            = 104209;"
df = pd.read_sql(query, con=db_connection)
df.head()

,compound_chembl_id,canonical_smiles,compound_key,assay_description,standard_type,standard_relation,standard_value,standard_units,activity_comment
0,CHEMBL1807053,CCC(CC)Nc1nc(C)c(nc1OC)c2ccc(OC(F)(F)F)cc2OC,"59, NGD 98-2",Inhibition of IL-6 at 4 uM,Inhibition,>,16.0,%,None
1,CHEMBL3137316,Cc1ncccc1NC(=O)c2ccc3c(CC[C@@H]4C[C@@](CC[C@@]...,BDBM140010,Fluorescence Polarization Ligand Binding Assay...,IC50,=,60.0,nM,191746
2,CHEMBL3647441,Cc1ncccc1NC(=O)c2ccc3c(CC[C@@H]4C[C@@](O)(CCC(...,BDBM140013,Fluorescence Polarization Ligand Binding Assay...,IC50,=,1.1,nM,191738
3,CHEMBL3647446,Cc1ncccc1NC(=O)c2ccc3c(CC[C@@H]4C[C@](O)(CC[C@...,BDBM140018,Fluorescence Polarization Ligand Binding Assay...,IC50,=,4.3,nM,191744
4,CHEMBL3647440,Cc1cnc(NC(=O)c2ccc3c(CC[C@@H]4C[C@](O)(CC[C@@]...,BDBM140012,Fluorescence Polarization Ligand Binding Assay...,IC50,=,4.0,nM,191735

tid = 104460

In [20]:
query = "SELECT m.chembl_id AS compound_chembl_id,   \
s.canonical_smiles,   \
r.compound_key,   \
a.description                   AS assay_description,   act.standard_type,   \
act.standard_relation,   \
act.standard_value,   \
act.standard_units,   \
act.activity_comment \
FROM compound_structures s,   \
molecule_dictionary m,   \
compound_records r,   \
docs d,   \
activities act,   \
assays a,   \
target_dictionary t \
WHERE s.molregno     = m.molregno \
AND m.molregno       = r.molregno \
AND r.record_id      = act.record_id \
AND r.doc_id         = d.doc_id \
AND act.assay_id     = a.assay_id \
AND a.tid            = t.tid \
AND t.tid            = 104460;"
#AND t.chembl_id      = 'CHEMBL1827';"
df = pd.read_sql(query, con=db_connection)
df.head()

,compound_chembl_id,canonical_smiles,compound_key,assay_description,standard_type,standard_relation,standard_value,standard_units,activity_comment
0,CHEMBL1950105,CC(=O)N[C@@H]1[C@@H](O)[C@@H](O)[C@@H](CO)O[C@...,"1, CS-OO",Binding affinity to recombinant midkine after ...,Kd,=,2030.00,nM,None
1,CHEMBL1950106,[Na+].[Na+].[Na+].[Na+].CC(=O)N[C@@H]1[C@@H](O...,"2, CS-EE",Binding affinity to recombinant midkine after ...,Kd,=,2.62,nM,None
2,CHEMBL1950107,[Na+].[Na+].CC(=O)N[C@@H]1[C@@H](O)[C@@H](OS(=...,"3, CS-AA",Binding affinity to recombinant midkine after ...,Kd,=,17.80,nM,None
3,CHEMBL1950108,[Na+].[Na+].[Na+].CC(=O)N[C@@H]1[C@@H](O)[C@@H...,CS-AE,Binding affinity to recombinant midkine after ...,Kd,=,11.60,nM,None

#### Find NASH proteins

In [21]:
target_df[target_df.pref_name.isin(nash_df["Protein name"])]

Empty DataFrame
Columns: [tid, target_type, pref_name, tax_id, organism, chembl_id, species_group_flag]
Index: []